// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2MIX4hhWlN9D_9U8_xPBX7LGCSspmdv4',
    appId: '1:1075306527680:web:d284c31f86fc62187ba625',
    messagingSenderId: '1075306527680',
    projectId: 'ecommerceapp-c7832',
    authDomain: 'ecommerceapp-c7832.firebaseapp.com',
    storageBucket: 'ecommerceapp-c7832.firebasestorage.app',
    measurementId: 'G-9DG2BRHM1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOUtKoK6LeKkXiIB8D13OfhHEIfDrbENI',
    appId: '1:1075306527680:android:8c6c4907a2a966037ba625',
    messagingSenderId: '1075306527680',
    projectId: 'ecommerceapp-c7832',
    storageBucket: 'ecommerceapp-c7832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf7FMV47d-vTj-VTLH9TFRbJDKmpa3vH0',
    appId: '1:1075306527680:ios:ed3fe7b2913b905e7ba625',
    messagingSenderId: '1075306527680',
    projectId: 'ecommerceapp-c7832',
    storageBucket: 'ecommerceapp-c7832.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf7FMV47d-vTj-VTLH9TFRbJDKmpa3vH0',
    appId: '1:1075306527680:ios:ed3fe7b2913b905e7ba625',
    messagingSenderId: '1075306527680',
    projectId: 'ecommerceapp-c7832',
    storageBucket: 'ecommerceapp-c7832.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2MIX4hhWlN9D_9U8_xPBX7LGCSspmdv4',
    appId: '1:1075306527680:web:f21a525a8b3c582d7ba625',
    messagingSenderId: '1075306527680',
    projectId: 'ecommerceapp-c7832',
    authDomain: 'ecommerceapp-c7832.firebaseapp.com',
    storageBucket: 'ecommerceapp-c7832.firebasestorage.app',
    measurementId: 'G-FTBBBE1QBF',
  );
}
